-- liquibase formatted sql

-- changeset rajan.vora:1642688273592-1
CREATE TABLE ERSSEC (RCN_ACTIVITY CHAR(6 BYTE) NOT NULL, RCN_NUMBER CHAR(8 BYTE) NOT NULL, EXHIBIT_DISPOSITION CHAR(1 BYTE), ACTION CHAR(2 BYTE), PQDR_RECOMMENDATION VARCHAR2(2 BYTE), PACKAGING_CONDITION VARCHAR2(2 BYTE), PACKAGING_CONDITION_NARR VARCHAR2(1000 BYTE), LABEL_MARKINGS VARCHAR2(1000 BYTE), MATERIAL_MARKINGS VARCHAR2(1000 BYTE), ORIGINATOR_MISC_NOTES VARCHAR2(1000 BYTE), ACTION_POINT_MISC_NOTES VARCHAR2(1000 BYTE), SCREENING_POINT_MISC_NOTES VARCHAR2(4000 BYTE), NAVY_AND_END_USER_STOCK VARCHAR2(1000 BYTE), EFFECTS_INSTALLED_MATERIAL VARCHAR2(1000 BYTE), TECH_ORDERING_DATA VARCHAR2(1000 BYTE), GOVT_SOURCE_INSP VARCHAR2(1000 BYTE), SUGGESTED_CORRECTIVE_ACTION VARCHAR2(1000 BYTE), END_SERVICE_USE VARCHAR2(1000 BYTE), SCREENING_POINT_RESOLUTION VARCHAR2(1000 BYTE), PQDR_RECO_JUSTIFICATION VARCHAR2(1000 BYTE), HISTORICAL_DATA VARCHAR2(4000 BYTE), DO_NOT_FORWARD_TO_ACTION_POINT CHAR(1 BYTE), CONSTRAINT PK_ERSSEC PRIMARY KEY (RCN_ACTIVITY, RCN_NUMBER));

-- changeset rajan.vora:1642688273592-2
CREATE TABLE ERSSECCTR (RCN_ACTIVITY CHAR(6 BYTE) NOT NULL, RCN_NUMBER CHAR(8 BYTE) NOT NULL, CONTRACT_NUMBER VARCHAR2(17 BYTE) NOT NULL, TDP_IRPOD_REVISION VARCHAR2(20 BYTE), CONSTRAINT PK_ERSSECCTR PRIMARY KEY (RCN_ACTIVITY, RCN_NUMBER, CONTRACT_NUMBER));

-- changeset rajan.vora:1642688273592-3
CREATE TABLE SAMSECSAD (RCN_ACTIVITY CHAR(6 BYTE) NOT NULL, RCN_NUMBER CHAR(6 BYTE) NOT NULL, REVISION_NUMBER NUMBER(2, 0) NOT NULL, ITEM_NUMBER NUMBER(2, 0) NOT NULL, CONDITION_TEXT VARCHAR2(4000 BYTE), RESOLUTION_TEXT VARCHAR2(4000 BYTE), CONSTRAINT PK_SAMSECSAD PRIMARY KEY (RCN_ACTIVITY, RCN_NUMBER, REVISION_NUMBER, ITEM_NUMBER));

-- changeset rajan.vora:1642688273592-4
CREATE TABLE RIBSEC (RIB_SERIAL_NUMBER VARCHAR2(6 BYTE) NOT NULL, RIB_REVISION_NUMBER NUMBER(2, 0) NOT NULL, SUBJECT_TEXT VARCHAR2(40 BYTE), SCOPE_TEXT VARCHAR2(40 BYTE), BACKGROUND_TEXT VARCHAR2(1000 BYTE), INSPECTION_ACTIONS_TEXT VARCHAR2(1000 BYTE), REMARKS VARCHAR2(1000 BYTE), REF_AUTHORITY VARCHAR2(200 BYTE), CONSTRAINT PK_RIBSEC PRIMARY KEY (RIB_SERIAL_NUMBER, RIB_REVISION_NUMBER));

-- changeset rajan.vora:1642688273592-5
CREATE TABLE ERSSECATTR (RCN_ACTIVITY CHAR(6 BYTE) NOT NULL, RCN_NUMBER CHAR(8 BYTE) NOT NULL, DEF_ATTRIBUTE NUMBER(2, 0) NOT NULL, QUANTITY_DEF NUMBER(6, 0), DESCRIPTION_OF_DEFICIENCY VARCHAR2(3000 BYTE) NOT NULL, BASIS_FOR_REJECT VARCHAR2(3000 BYTE) NOT NULL, DEFECT_VALID VARCHAR2(2 BYTE), INVALID_JUSTIFICATION VARCHAR2(3000 BYTE), TECHNICALLY_ACCEPTABLE VARCHAR2(2 BYTE), MINOR_REPAIR VARCHAR2(3000 BYTE), TECH_RECEIPT_INSP_ADEQUATE VARCHAR2(2 BYTE), RECOMMENDED_TECH_INSP_REVS VARCHAR2(3000 BYTE), VENDOR_DCMA_ACTION VARCHAR2(2 BYTE), RECOMMENDED_ACTIONS VARCHAR2(3000 BYTE), DCMA_INSP_ADEQUATE VARCHAR2(2 BYTE), RECOMMENDED_DCMA_REVS VARCHAR2(3000 BYTE), TECH_ORDERING_DATA_ADEQUATE VARCHAR2(2 BYTE), RECOMMENDED_TECH_ORDER_REVS VARCHAR2(3000 BYTE), STOCK_SCREENING_RECOMMENDED VARCHAR2(2 BYTE), SCREENING_JUSTIFICATION VARCHAR2(3000 BYTE), INSTALLED_MATERIAL VARCHAR2(2 BYTE), INSTALLED_MATERIAL_ACTIONS VARCHAR2(2 BYTE), INSTALLED_MATERIAL_ACTION_NARR VARCHAR2(3000 BYTE), CONSTRAINT PK_ERSSECATTR PRIMARY KEY (RCN_ACTIVITY, RCN_NUMBER, DEF_ATTRIBUTE));

-- changeset rajan.vora:1642688273592-6
CREATE TABLE RIBSECATTR (RIB_SERIAL_NUMBER VARCHAR2(6 BYTE) NOT NULL, RIB_REVISION_NUMBER NUMBER(2, 0) NOT NULL, INSPECTION_ATTRIBUTE NUMBER(2, 0) NOT NULL, INSPECTION_ATTRIBUTE_DISC VARCHAR2(200 BYTE), CONSTRAINT PK_RIBSECATTR PRIMARY KEY (RIB_SERIAL_NUMBER, RIB_REVISION_NUMBER, INSPECTION_ATTRIBUTE));

-- changeset rajan.vora:1642688273592-7
CREATE TABLE RIMS_SEC_REMARKS (REPORTING_ACTIVITY CHAR(6 BYTE) NOT NULL, SERIAL_NUMBER VARCHAR2(9 BYTE) NOT NULL, REVISION_NUMBER NUMBER(2, 0) NOT NULL, ITEM_NUMBER NUMBER(2, 0) NOT NULL, REMARKS VARCHAR2(1000 BYTE) NOT NULL, REMARKS_IND CHAR(1 BYTE), REMARKS_SIGNED_BY VARCHAR2(12 BYTE), REMARKS_DATE date, REMARKS_SIGNATURE VARCHAR2(75 BYTE), CONSTRAINT PK_RIMS_SEC_REMARKS PRIMARY KEY (REPORTING_ACTIVITY, SERIAL_NUMBER, REVISION_NUMBER, ITEM_NUMBER));

-- changeset rajan.vora:1642688273592-8
CREATE TABLE RIMS_SEC_RIDL (REPORTING_ACTIVITY CHAR(6 BYTE) NOT NULL, SERIAL_NUMBER VARCHAR2(9 BYTE) NOT NULL, REVISION_NUMBER NUMBER(2, 0) NOT NULL, ITEM_NUMBER NUMBER(2, 0) NOT NULL, CONDITION_TEXT VARCHAR2(4000 BYTE), RESOLUTION_TEXT VARCHAR2(4000 BYTE), METRIC_REMARKS VARCHAR2(1000 BYTE), CONSTRAINT PK_RIMS_SEC_RIDL PRIMARY KEY (REPORTING_ACTIVITY, SERIAL_NUMBER, REVISION_NUMBER, ITEM_NUMBER));

-- changeset rajan.vora:1642688273592-9
CREATE TABLE SAMSECREM (RCN_ACTIVITY CHAR(6 BYTE) NOT NULL, RCN_NUMBER CHAR(6 BYTE) NOT NULL, REVISION_NUMBER NUMBER(2, 0) NOT NULL, ITEM_NUMBER NUMBER(2, 0) NOT NULL, REMARKS VARCHAR2(1000 BYTE), REMARKS_IND CHAR(1 BYTE), REMARKS_SIGNED_BY VARCHAR2(12 BYTE), REMARKS_DATE date, REMARKS_SIGNATURE VARCHAR2(75 BYTE), CONSTRAINT PK_SAMSECREM PRIMARY KEY (RCN_ACTIVITY, RCN_NUMBER, REVISION_NUMBER, ITEM_NUMBER));

-- changeset rajan.vora:1642688273592-10
CREATE OR REPLACE FORCE VIEW "RIMS_SECRIDL_SEARCHDETAIL_VIEW" ("REPORTING_ACTIVITY", "SERIAL_NUMBER", "REVISION_NUMBER", "LOW_SERIAL_NUMBER", "MATERIAL_LEVEL_CODE", "ITEM_NUMBER", "CONDITION_TEXT", "RESOLUTION_TEXT", "NSN_FSC", "NSN_NIIN", "FSC_MATERIAL_DESCRIPTION", "DRAWING_NUMBER", "RIDL_ID", "RIDL_TYPE", "METRIC1", "METRIC2", "INSPECTION_ATTRIBUTE", "INSPECTION_ATTRIBUTE_LITERAL", "PREENGINEERED_IND", "CATEGORY") AS SELECT
   rims_mir.reporting_activity,
   rims_mir.serial_number,
   rims_mir.revision_number,
   rims_mir.low_serial_number,
   rims_mir.material_level_code,
   rims_ridl.item_number,
   rims_sec_ridl.condition_text,
   rims_sec_ridl.resolution_text,
   rims_mir.nsn_fsc,
   rims_mir.nsn_niin,
   rims_mir.fsc_material_description,
   rims_mir.drawing_number,
   rims_ridl.ridl_id,
   rims_ridl.ridl_type,
   rims_ridl.metric1,
   rims_ridl.metric2,
   rims_ridl.inspection_attribute,
   mir_inspection_attribute.literal inspection_attribute_literal,
   rims_ridl.preengineered_ind,
   rims_ridl.category
FROM rims_mir, rims_ridl, rims_sec_ridl, mir_inspection_attribute
WHERE rims_mir.reporting_activity = rims_ridl.reporting_activity
AND rims_mir.serial_number = rims_ridl.serial_number
AND rims_mir.revision_number = rims_ridl.revision_number
AND rims_mir.material_level_code IN (4, 5, 7, 9, 10)
AND rims_ridl.reporting_activity = rims_sec_ridl.reporting_activity
AND rims_ridl.serial_number = rims_sec_ridl.serial_number
AND rims_ridl.revision_number = rims_sec_ridl.revision_number
AND rims_ridl.item_number = rims_sec_ridl.item_number
AND rims_ridl.inspection_attribute = mir_inspection_attribute.code(+);

-- changeset rajan.vora:1642688273592-11
CREATE SEQUENCE ERSSECREM_SEQ START WITH 141 MAXVALUE 9999999999999999999999999999 ORDER CYCLE;

-- changeset rajan.vora:1642688273592-12
CREATE SEQUENCE SECATTACHMENTS_ID START WITH 1441 MAXVALUE 9999999999999999999999999999;

-- changeset rajan.vora:1642688273592-13
CREATE TABLE ERSSECATTR_ARCHIVE (RCN_ACTIVITY CHAR(6 BYTE) NOT NULL, RCN_NUMBER CHAR(8 BYTE) NOT NULL, DEF_ATTRIBUTE NUMBER(2, 0) NOT NULL, QUANTITY_DEF NUMBER(6, 0), DESCRIPTION_OF_DEFICIENCY VARCHAR2(3000 BYTE) NOT NULL, BASIS_FOR_REJECT VARCHAR2(3000 BYTE) NOT NULL, DEFECT_VALID VARCHAR2(2 BYTE), INVALID_JUSTIFICATION VARCHAR2(3000 BYTE), TECHNICALLY_ACCEPTABLE VARCHAR2(2 BYTE), MINOR_REPAIR VARCHAR2(3000 BYTE), TECH_RECEIPT_INSP_ADEQUATE VARCHAR2(2 BYTE), RECOMMENDED_TECH_INSP_REVS VARCHAR2(3000 BYTE), VENDOR_DCMA_ACTION VARCHAR2(2 BYTE), RECOMMENDED_ACTIONS VARCHAR2(3000 BYTE), DCMA_INSP_ADEQUATE VARCHAR2(2 BYTE), RECOMMENDED_DCMA_REVS VARCHAR2(3000 BYTE), TECH_ORDERING_DATA_ADEQUATE VARCHAR2(2 BYTE), RECOMMENDED_TECH_ORDER_REVS VARCHAR2(3000 BYTE), STOCK_SCREENING_RECOMMENDED VARCHAR2(2 BYTE), SCREENING_JUSTIFICATION VARCHAR2(3000 BYTE), INSTALLED_MATERIAL VARCHAR2(2 BYTE), INSTALLED_MATERIAL_ACTIONS VARCHAR2(2 BYTE), INSTALLED_MATERIAL_ACTION_NARR VARCHAR2(3000 BYTE), ARCHIVE_DATE date NOT NULL, DELETE_ACTIVITY VARCHAR2(12 BYTE));

-- changeset rajan.vora:1642688273592-14
CREATE TABLE ERSSECCTR_ARCHIVE (RCN_ACTIVITY CHAR(6 BYTE) NOT NULL, RCN_NUMBER CHAR(8 BYTE) NOT NULL, CONTRACT_NUMBER VARCHAR2(17 BYTE) NOT NULL, TDP_IRPOD_REVISION VARCHAR2(20 BYTE), ARCHIVE_DATE date NOT NULL, DELETE_ACTIVITY VARCHAR2(12 BYTE));

-- changeset rajan.vora:1642688273592-15
CREATE TABLE ERSSECREMARKS (REMARK_ID NUMBER NOT NULL, RECORD_TYPE VARCHAR2(5 BYTE) NOT NULL, KEY_INFO VARCHAR2(25 BYTE) NOT NULL, REMARK_NARR VARCHAR2(1000 BYTE) NOT NULL, UPDATE_POINT NUMBER, UPDATE_DATE date, SIGNED_BY VARCHAR2(12 BYTE), SIGNED_DATE date, USER_SIGNATURE VARCHAR2(75 BYTE), CONSTRAINT PK_ERSSECREMARKS PRIMARY KEY (REMARK_ID, RECORD_TYPE, KEY_INFO));

-- changeset rajan.vora:1642688273592-16
CREATE TABLE ERSSEC_ARCHIVE (RCN_ACTIVITY CHAR(6 BYTE) NOT NULL, RCN_NUMBER CHAR(8 BYTE) NOT NULL, EXHIBIT_DISPOSITION CHAR(1 BYTE), ACTION CHAR(2 BYTE), PQDR_RECOMMENDATION VARCHAR2(2 BYTE), PACKAGING_CONDITION VARCHAR2(2 BYTE), PACKAGING_CONDITION_NARR VARCHAR2(1000 BYTE), LABEL_MARKINGS VARCHAR2(1000 BYTE), MATERIAL_MARKINGS VARCHAR2(1000 BYTE), ORIGINATOR_MISC_NOTES VARCHAR2(1000 BYTE), ACTION_POINT_MISC_NOTES VARCHAR2(1000 BYTE), SCREENING_POINT_MISC_NOTES VARCHAR2(4000 BYTE), NAVY_AND_END_USER_STOCK VARCHAR2(1000 BYTE), EFFECTS_INSTALLED_MATERIAL VARCHAR2(1000 BYTE), TECH_ORDERING_DATA VARCHAR2(1000 BYTE), GOVT_SOURCE_INSP VARCHAR2(1000 BYTE), SUGGESTED_CORRECTIVE_ACTION VARCHAR2(1000 BYTE), END_SERVICE_USE VARCHAR2(1000 BYTE), SCREENING_POINT_RESOLUTION VARCHAR2(1000 BYTE), PQDR_RECO_JUSTIFICATION VARCHAR2(1000 BYTE), HISTORICAL_DATA VARCHAR2(4000 BYTE), ARCHIVE_DATE date NOT NULL, DELETE_ACTIVITY VARCHAR2(12 BYTE), DO_NOT_FORWARD_TO_ACTION_POINT CHAR(1 BYTE));

-- changeset rajan.vora:1642688273592-17
CREATE TABLE RIBSECATTR_ARCHIVE (RIB_SERIAL_NUMBER VARCHAR2(6 BYTE), RIB_REVISION_NUMBER NUMBER(2, 0), INSPECTION_ATTRIBUTE NUMBER(2, 0), INSPECTION_ATTRIBUTE_DISC VARCHAR2(200 BYTE), ARCHIVE_DATE date NOT NULL, DELETE_ACTIVITY VARCHAR2(12 BYTE));

-- changeset rajan.vora:1642688273592-18
CREATE TABLE RIBSEC_ARCHIVE (RIB_SERIAL_NUMBER VARCHAR2(6 BYTE), RIB_REVISION_NUMBER NUMBER(2, 0), SUBJECT_TEXT VARCHAR2(40 BYTE), SCOPE_TEXT VARCHAR2(40 BYTE), BACKGROUND_TEXT VARCHAR2(1000 BYTE), INSPECTION_ACTIONS_TEXT VARCHAR2(1000 BYTE), REMARKS VARCHAR2(1000 BYTE), REF_AUTHORITY VARCHAR2(200 BYTE), ARCHIVE_DATE date NOT NULL, DELETE_ACTIVITY VARCHAR2(12 BYTE));

-- changeset rajan.vora:1642688273592-19
CREATE TABLE RIMS_SEC_REMARKS_ARCHIVE (REPORTING_ACTIVITY CHAR(6 BYTE) NOT NULL, SERIAL_NUMBER VARCHAR2(9 BYTE) NOT NULL, REVISION_NUMBER NUMBER(2, 0) NOT NULL, ITEM_NUMBER NUMBER(2, 0) NOT NULL, REMARKS VARCHAR2(1000 BYTE) NOT NULL, REMARKS_IND CHAR(1 BYTE), REMARKS_SIGNED_BY VARCHAR2(12 BYTE), REMARKS_DATE date, REMARKS_SIGNATURE VARCHAR2(75 BYTE), ARCHIVE_DATE date NOT NULL, DELETE_ACTIVITY VARCHAR2(12 BYTE));

-- changeset rajan.vora:1642688273592-20
CREATE TABLE RIMS_SEC_RIDL_ARCHIVE (REPORTING_ACTIVITY CHAR(6 BYTE) NOT NULL, SERIAL_NUMBER VARCHAR2(9 BYTE) NOT NULL, REVISION_NUMBER NUMBER(2, 0) NOT NULL, ITEM_NUMBER NUMBER(2, 0) NOT NULL, CONDITION_TEXT VARCHAR2(4000 BYTE), RESOLUTION_TEXT VARCHAR2(4000 BYTE), METRIC_REMARKS VARCHAR2(1000 BYTE), DELETE_ACTIVITY VARCHAR2(12 BYTE), ARCHIVE_DATE date NOT NULL);

-- changeset rajan.vora:1642688273592-21
CREATE TABLE SAMSECREM_ARCHIVE (RCN_ACTIVITY CHAR(6 BYTE), RCN_NUMBER CHAR(6 BYTE), REVISION_NUMBER NUMBER(2, 0), ITEM_NUMBER NUMBER(2, 0), REMARKS VARCHAR2(1000 BYTE), REMARKS_IND CHAR(1 BYTE), REMARKS_SIGNED_BY VARCHAR2(12 BYTE), REMARKS_DATE date, REMARKS_SIGNATURE VARCHAR2(75 BYTE), ARCHIVE_DATE date NOT NULL, DELETE_ACTIVITY VARCHAR2(12 BYTE));

-- changeset rajan.vora:1642688273592-22
CREATE TABLE SAMSECSAD_ARCHIVE (RCN_ACTIVITY CHAR(6 BYTE), RCN_NUMBER CHAR(6 BYTE), REVISION_NUMBER NUMBER(2, 0), ITEM_NUMBER NUMBER(2, 0), CONDITION_TEXT VARCHAR2(4000 BYTE), RESOLUTION_TEXT VARCHAR2(4000 BYTE), ARCHIVE_DATE date NOT NULL, DELETE_ACTIVITY VARCHAR2(12 BYTE));

-- changeset rajan.vora:1642688273592-23
CREATE TABLE SECAPPS_ATTACHMENTS (ATTACHMENT_ID NUMBER(7, 0) NOT NULL, RECORD_TYPE CHAR(5 BYTE) NOT NULL, KEY_INFO VARCHAR2(25 BYTE) NOT NULL, MIME_TYPE VARCHAR2(100 BYTE), FILE_DESCRIPTION VARCHAR2(500 BYTE), FILE_COMMENTS VARCHAR2(500 BYTE), FILE_NAME VARCHAR2(100 BYTE), UPDATE_ACTIVITY VARCHAR2(12 BYTE), ADDED_DATE date, UPDATE_DATE date, ATTACHMENT_DATA BLOB, GOVT_ACCESS_IND CHAR(1 BYTE), CUI_CODE NUMBER(3, 0), LDC_CODE NUMBER(2, 0), CONSTRAINT PK_SECAPPS_ATTACHMENTS PRIMARY KEY (ATTACHMENT_ID));

-- changeset rajan.vora:1642688273592-24
CREATE INDEX I_ERSSECATTR_ARCHIVE ON ERSSECATTR_ARCHIVE(RCN_ACTIVITY, RCN_NUMBER, ARCHIVE_DATE);

-- changeset rajan.vora:1642688273592-25
CREATE INDEX I_ERSSECCTR_ARCHIVE ON ERSSECCTR_ARCHIVE(RCN_ACTIVITY, RCN_NUMBER, ARCHIVE_DATE);

-- changeset rajan.vora:1642688273592-26
CREATE INDEX I_ERSSEC_ARCHIVE ON ERSSEC_ARCHIVE(RCN_ACTIVITY, RCN_NUMBER, ARCHIVE_DATE);

-- changeset rajan.vora:1642688273592-27
CREATE INDEX I_RIBSECATTR_ARCHIVE ON RIBSECATTR_ARCHIVE(RIB_SERIAL_NUMBER, RIB_REVISION_NUMBER, ARCHIVE_DATE);

-- changeset rajan.vora:1642688273592-28
CREATE INDEX I_RIBSEC_ARCHIVE ON RIBSEC_ARCHIVE(RIB_SERIAL_NUMBER, RIB_REVISION_NUMBER, ARCHIVE_DATE);

-- changeset rajan.vora:1642688273592-29
CREATE INDEX I_RIMS_SEC_REMARKS_ARCHIVE ON RIMS_SEC_REMARKS_ARCHIVE(REPORTING_ACTIVITY, SERIAL_NUMBER, REVISION_NUMBER, ARCHIVE_DATE);

-- changeset rajan.vora:1642688273592-30
CREATE INDEX I_RIMS_SEC_RIDL_ARCHIVE ON RIMS_SEC_RIDL_ARCHIVE(REPORTING_ACTIVITY, SERIAL_NUMBER, REVISION_NUMBER, ARCHIVE_DATE);

-- changeset rajan.vora:1642688273592-31
CREATE INDEX I_SAMSECREM_ARCHIVE ON SAMSECREM_ARCHIVE(RCN_ACTIVITY, RCN_NUMBER, REVISION_NUMBER, ARCHIVE_DATE);

-- changeset rajan.vora:1642688273592-32
CREATE INDEX I_SAMSECSAD_ARCHIVE ON SAMSECSAD_ARCHIVE(RCN_ACTIVITY, RCN_NUMBER, REVISION_NUMBER, ARCHIVE_DATE);

-- changeset rajan.vora:1642688273592-33
CREATE INDEX I_SECAPPS_ATTACHMENTS_KEY ON SECAPPS_ATTACHMENTS(KEY_INFO);

-- changeset rajan.vora:1642688273592-34
ALTER TABLE ERSSEC ADD CONSTRAINT FK_ERSSEC FOREIGN KEY (RCN_ACTIVITY, RCN_NUMBER) REFERENCES ERS (RCN_ACTIVITY, RCN_NUMBER) ON DELETE CASCADE;

-- changeset rajan.vora:1642688273592-35
ALTER TABLE ERSSECATTR ADD CONSTRAINT FK_ERSSECATTR FOREIGN KEY (RCN_ACTIVITY, RCN_NUMBER) REFERENCES SEC.ERSSEC (RCN_ACTIVITY, RCN_NUMBER) ON DELETE CASCADE;

-- changeset rajan.vora:1642688273592-36
ALTER TABLE ERSSECCTR ADD CONSTRAINT FK_ERSSECCTR FOREIGN KEY (RCN_ACTIVITY, RCN_NUMBER, CONTRACT_NUMBER) REFERENCES ERSCTR (RCN_ACTIVITY, RCN_NUMBER, CONTRACT_NUMBER) ON DELETE CASCADE;

-- changeset rajan.vora:1642688273592-37
ALTER TABLE RIBSEC ADD CONSTRAINT FK_RIBSEC FOREIGN KEY (RIB_SERIAL_NUMBER, RIB_REVISION_NUMBER) REFERENCES RIB (RIB_SERIAL_NUMBER, RIB_REVISION_NUMBER) ON DELETE CASCADE;

-- changeset rajan.vora:1642688273592-38
ALTER TABLE RIBSECATTR ADD CONSTRAINT FK_RIBSECATTR FOREIGN KEY (RIB_SERIAL_NUMBER, RIB_REVISION_NUMBER) REFERENCES SEC.RIBSEC (RIB_SERIAL_NUMBER, RIB_REVISION_NUMBER) ON DELETE CASCADE;

-- changeset rajan.vora:1642688273592-39
ALTER TABLE RIMS_SEC_REMARKS ADD CONSTRAINT FK_RIMS_SEC_REMARKS FOREIGN KEY (REPORTING_ACTIVITY, SERIAL_NUMBER, REVISION_NUMBER) REFERENCES RIMS_MAIN (REPORTING_ACTIVITY, KEY_SERIAL_NUMBER, REVISION_NUMBER) ON DELETE CASCADE;

-- changeset rajan.vora:1642688273592-40
ALTER TABLE RIMS_SEC_RIDL ADD CONSTRAINT FK_RIMS_SEC_RIDL FOREIGN KEY (REPORTING_ACTIVITY, SERIAL_NUMBER, REVISION_NUMBER, ITEM_NUMBER) REFERENCES RIMS_RIDL (REPORTING_ACTIVITY, SERIAL_NUMBER, REVISION_NUMBER, ITEM_NUMBER) ON DELETE CASCADE;

-- changeset rajan.vora:1642688273592-41
ALTER TABLE SAMSECREM ADD CONSTRAINT FK_SAMSECREM FOREIGN KEY (RCN_ACTIVITY, RCN_NUMBER, REVISION_NUMBER) REFERENCES SAM (RCN_ACTIVITY, RCN_NUMBER, REVISION_NUMBER) ON DELETE CASCADE;

-- changeset rajan.vora:1642688273592-42
ALTER TABLE SAMSECSAD ADD CONSTRAINT FK_SAMSECSAD FOREIGN KEY (RCN_ACTIVITY, RCN_NUMBER, REVISION_NUMBER, ITEM_NUMBER) REFERENCES SAMSAD (RCN_ACTIVITY, RCN_NUMBER, REVISION_NUMBER, ITEM_NUMBER) ON DELETE CASCADE;

-- changeset rajan.vora:1642688273592-43
ALTER TABLE SECAPPS_ATTACHMENTS ADD CONSTRAINT FK_SECAPPS_ATTACHMENTS_CUI FOREIGN KEY (CUI_CODE) REFERENCES CUI (CODE);

-- changeset rajan.vora:1642688273592-44
ALTER TABLE SECAPPS_ATTACHMENTS ADD CONSTRAINT FK_SECAPPS_ATTACHMENTS_LDC FOREIGN KEY (LDC_CODE) REFERENCES LDC (CODE);

